services:
  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./nutriburger-backend
    env_file:
      - nutriburger-backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: "no"

  frontend:
    build: ./nutriburger-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: "no"

volumes:
  db-data: