CREATE INDEX idx_produto_categoria ON produtos(categoria_id);
CREATE INDEX idx_produto_ingrediente_produto ON produto_ingrediente(produto_id);
CREATE INDEX idx_produto_ingrediente_ingrediente ON produto_ingrediente(ingrediente_id);
CREATE INDEX idx_dados_nutricionais_produto ON produto_dados_nutricionais(produto_id);